### ISSUE TITLE
python 2.6 incompatibility

### ISSUE THREAD

**Issue by stanis** [major/rackspace-clouddns-gui#17]
The thing doesn't work with python 2.6.

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/gunicorn/arbiter.py", line 422, in spawn_worker
    worker.init_process()
  File "/usr/lib/pymodules/python2.6/gunicorn/workers/base.py", line 95, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/pymodules/python2.6/gunicorn/app/base.py", line 101, in wsgi
    self.callable = self.load()
  File "/usr/lib/pymodules/python2.6/gunicorn/app/wsgiapp.py", line 24, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/pymodules/python2.6/gunicorn/util.py", line 178, in import_app
    **import**(module)
  File "/var/www/clouddns/clouddns-gui.py", line 223
     formvars = {x:y[0] for x, y in dict(request.form).iteritems()}
                          ^
 SyntaxError: invalid syntax

This is Python 2.7 syntax. So we have a problem using this tool with Python 2.6 (debian stable).

**Comment by shawnholt** [comment]
Ahh ... that was my problem.  Cpanel requires python 2.6 (centos).  any quick fix?

**Comment by stanis** [comment]
> > > a={"a":1,"b":2}
> > > for b in a.iteritems():
> > > ...   (x,y)=b
> > > ...   print x,y
> > > ?
